# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WeatherApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  
  pod 'Alamofire', '~> 4.4'
  
  use_frameworks!

  # Pods for WeatherApp

  target 'WeatherAppTests' do
  
    pod 'Alamofire', '~> 4.4'
    
  end

  target 'WeatherAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
